// Received from client types:
exports.USER_CONNECTED = 'USER_CONNECTED';
exports.USER_DISCONNECTED = 'USER_DISCONNECTED';
exports.CREATED_CHAT_ROOM = 'CREATED_CHAT_ROOM';
exports.UPDATE_AVATAR = 'UPDATE_AVATAR';

// exports.DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE';

// Return to client types:
exports.OUTPUT_CHAT_MESSAGE = 'OUTPUT_CHAT_MESSAGE';
exports.DELETED_CHAT_MESSAGE = 'DELETED_CHAT_MESSAGE';
exports.EMIT_CREATED_CHAT_ROOM = 'EMIT_CREATED_CHAT_ROOM';
exports.MEMBERS_JOIN_NEW_CHAT_ROOM = 'MEMBERS_JOIN_NEW_CHAT_ROOM';
