// Received from client types:
exports.USER_CONNECTED = 'USER_CONNECTED';
exports.USER_DISCONNECTED = 'USER_DISCONNECTED';
// exports.DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE';

// Return to client types:
exports.OUTPUT_CHAT_MESSAGE = 'OUTPUT_CHAT_MESSAGE';
exports.DELETED_CHAT_MESSAGE = 'DELETED_CHAT_MESSAGE';
