// CHATMESSAGE TYPES
// Send to server / backend types:
export const GET_ALL_CHAT_MESSAGES = 'GET_ALL_CHAT_MESSAGES';
export const CREATE_CHAT_MESSAGE = 'CREATE_CHAT_MESSAGE';
export const SET_LAST_CHAT_MESSAGE = 'SET_LAST_CHAT_MESSAGE';
export const DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE';

// Receive from server / backed types:
export const OUTPUT_CHAT_MESSAGE = 'OUTPUT_CHAT_MESSAGE';
export const DELETED_CHAT_MESSAGE = 'DELETED_CHAT_MESSAGE';
export const EMIT_CREATED_CHAT_ROOM = 'EMIT_CREATED_CHAT_ROOM';

// USER TYPES - client side
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// USER TYPES - sent to backend
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';

// Update the connected userlist in the redux state. (Authroute)
export const UPDATE_CONNECTED_USERLIST = 'UPDATE_CONNECTED_USERLIST';
export const GET_ALL_USERS = 'GET_ALL_USERS';

// CHAT ROOM TYPES
export const SET_ACTIVE_CHATROOM = 'SET_ACTIVE_CHATROOM';
export const SET_USER_CHATROOMS = 'SET_USER_CHATROOMS';
export const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM';
export const CREATED_CHAT_ROOM = 'CREATED_CHAT_ROOM';
export const MEMBERS_JOIN_NEW_CHAT_ROOM = 'MEMBERS_JOIN_NEW_CHAT_ROOM';
export const LEAVE_CHATROOM = 'LEAVE_CHATROOM';
export const ADD_USERS_TO_CHATROOM = 'ADD_USERS_TO_CHATROOM';
export const ADDED_USERS_TO_CHATROOM = 'ADDED_USERS_TO_CHATROOM';

// UI TYPES
export const TOGGLE_CHAT = 'TOGGLE_CHAT';
export const TOGGLE_CONTACTS = 'TOGGLE_CONTACTS';
export const SET_NO_ACTIVE_CHATROOM = 'SET_NO_ACTIVE_CHATROOM';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const LEFT_CHATROOM = 'LEFT_CHATROOM';
export const SET_UNREAD_MESSAGES = 'SET_UNREAD_MESSAGES';
export const MARK_MESSAGES_READ = ' MARK_MESSAGES_READ';

// THEME TYPES
export const SET_LIGHT_THEME = 'SET_LIGHT_THEME';
export const SET_DARK_THEME = 'SET_DARK_THEME';

// ERROR TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// SOCKET TYPES
export const SEND_USER_SOCKET = 'SEND_USER_SOCKET';
export const SEND_BACK_USER_SOCKET = 'SEND_BACK_USER_SOCKET';
export const UPDATE_USERS_WITH_SOCKETS = 'UPDATE_USERS_WITH_SOCKETS';
